### ISSUE TITLE
04-Rewrite UserService and UserServiceImpl

### ISSUE THREAD

**Issue by ted0zh** [Spectatori/Exp-banking#4]
-Add update method to userService
-Rewrite the save method in userServiceImpl(copy the save method from TransactionsServiceImpl) but dont use User, use UserDTO and convert it to entity

**Comment by ted0zh** [comment]
dont push, make pull request first

**Comment by MartinKanev1** [comment]
almost sure im done
Created userService
Rewritetten the save method in userServiceImpl (but not 100% sure..better to check again)
